### ISSUE TITLE
SerialGps_App is not working on Raspberry Pi 5 - PIGPIO ERROR: PI_INIT_FAILED; pigpio initialisation failed

### ISSUE THREAD

**Issue by SergeySn** [Pi4J/pi4j-example-components#64]
I am trying to run SerialGps_App example on Raspberry Pi 5.  
So, I updated pi4j.version to 2.6.0
But I get this error:

`
Launching target [SerialGps_App (com.pi4j.catalog.applications.SerialGps_App)]
GPS demo started
com.pi4j.library.pigpio.PiGpioException: PIGPIO ERROR: PI_INIT_FAILED; pigpio initialisation failed
	at com.pi4j.library.pigpio@2.6.0/com.pi4j.library.pigpio.impl.PiGpioBase.validateResult(PiGpioBase.java:265)
	at com.pi4j.library.pigpio@2.6.0/com.pi4j.library.pigpio.impl.PiGpioBase.validateResult(PiGpioBase.java:251)
	at com.pi4j.library.pigpio@2.6.0/com.pi4j.library.pigpio.impl.PiGpioNativeImpl.gpioInitialise(PiGpioNativeImpl.java:106)
	at com.pi4j.library.pigpio@2.6.0/com.pi4j.library.pigpio.PiGpio.initialize(PiGpio.java:159)
	at com.pi4j.plugin.pigpio@2.6.0/com.pi4j.plugin.pigpio.provider.serial.PiGpioSerialProviderImpl.create(PiGpioSerialProviderImpl.java:71)
	at com.pi4j.plugin.pigpio@2.6.0/com.pi4j.plugin.pigpio.provider.serial.PiGpioSerialProviderImpl.create(PiGpioSerialProviderImpl.java:42)
	at com.pi4j@2.6.0/com.pi4j.context.Context.create(Context.java:352)
	at com.pi4j@2.6.0/com.pi4j.internal.IOCreator.create(IOCreator.java:58)
	at com.pi4j@2.6.0/com.pi4j.internal.IOCreator.create(IOCreator.java:146)
	at com.pi4j.example@0.0.1/com.pi4j.catalog.components.base.SerialDevice.<init>(SerialDevice.java:30)
	at com.pi4j.example@0.0.1/com.pi4j.catalog.components.SerialGps.<init>(SerialGps.java:49)
	at com.pi4j.example@0.0.1/com.pi4j.catalog.applications.SerialGps_App.execute(SerialGps_App.java:15)
	at com.pi4j.example@0.0.1/com.pi4j.catalog.Launcher$ApplicationRunner.run(Launcher.java:278)
	at com.pi4j.example@0.0.1/com.pi4j.catalog.Launcher$Target.run(Launcher.java:253)
	at com.pi4j.example@0.0.1/com.pi4j.catalog.Launcher.run(Launcher.java:140)
	at info.picocli@4.7.4/picocli.CommandLine.executeUserObject(CommandLine.java:2026)
	at info.picocli@4.7.4/picocli.CommandLine.access$1500(CommandLine.java:148)
	at info.picocli@4.7.4/picocli.CommandLine$RunLast.executeUserObjectOfLastSubcommandWithSameParent(CommandLine.java:2461)
	at info.picocli@4.7.4/picocli.CommandLine$RunLast.handle(CommandLine.java:2453)
	at info.picocli@4.7.4/picocli.CommandLine$RunLast.handle(CommandLine.java:2415)
	at info.picocli@4.7.4/picocli.CommandLine$AbstractParseResultHandler.execute(CommandLine.java:2273)
	at info.picocli@4.7.4/picocli.CommandLine$RunLast.execute(CommandLine.java:2417)
	at info.picocli@4.7.4/picocli.CommandLine.execute(CommandLine.java:2170)
	at com.pi4j.example@0.0.1/com.pi4j.catalog.Launcher.execute(Launcher.java:207)
	at com.pi4j.example@0.0.1/com.pi4j.catalog.Launcher.main(Launcher.java:82)
`
The full log is attached:
[log.txt](https://github.com/Pi4J/pi4j-example-components/files/15360972/log.txt)

Any ideas what might be wrong?

**Comment by SergeySn** [comment]
Any update on this?

**Comment by Clobo3d** [comment]
I have the same problem.
